import { Config, ConfigFile } from './types.js';

export const defaultConfig: Config = {
  branchDescriptionChars: '[a-z0-9_-]',
  branchMaxLength: 92,
  branchMinLength: 4,
  branchNameFeedback: '',
  branchNamePattern: '',
  branchSeparator: '/',
  branchesToSkip: ['(no branch)', 'no branch'],
  changeType: [
    'build',
    'fix',
    'feat',
    'chore',
    'ci',
    'docs',
    'perf',
    'refactor',
    'style',
    'test',
  ],
  commitMessagePattern: '.*',
  configFile: ConfigFile.PackageJSON,
  globalScope: '',
  mainBranches: ['master', 'main', 'dev', 'test'],
  ticketKey: '',
  ticketNumberMaxLength: 0,
  ticketNumberMinLength: 1,
  ticketSeparator: '',
};
